---
- hosts: hdp
  sudo: True
  vars:
    hdp_repo: http://public-repo-1.hortonworks.com
    vagrant_deps_path: /vagrant/deps
    vagrant_script_path: /vagrant/scripts
  tasks:
    - name: Download ambari.repo
      get_url: url={{ hdp_repo }}/ambari/centos6/1.x/updates/1.7.0/ambari.repo dest=/etc/yum.repos.d/ambari.repo mode=0644

    - name: Install Ambari Server
      yum: name=ambari-server state=present

    - name: Download Java for Ambari
      get_url: url={{ hdp_repo }}/ARTIFACTS/{{ item }} dest={{ vagrant_deps_path }}/{{ item }}
      with_items:
        - jdk-7u67-linux-x64.tar.gz
        - UnlimitedJCEPolicyJDK7.zip

    - name: Copy Java to Ambari resources
      command: cp {{ vagrant_deps_path }}/{{ item }} /var/lib/ambari-server/resources/{{ item }} creates=/var/lib/ambari-server/resources/{{ item }}
      with_items:
        - jdk-7u67-linux-x64.tar.gz
        - UnlimitedJCEPolicyJDK7.zip

    - name: Setup ambari-server
      shell: ambari-server setup -s

    - name: Increase Ambari timeout
      sudo : yes
      command: sed -i "s/agent.task.timeout=900/agent.task.timeout=2000/" /etc/ambari-server/conf/ambari.properties

    - name: Ensure Ambari server running
      service: name=ambari-server state=restarted enabled=yes

    - wait_for: port=8080 delay=3

    - name: Ambari agent bootstrap
      sudo: no
      command: python {{ vagrant_script_path }}/bootstrap_ambari_agent.py

    - name: Add cluster blueprint to Ambari
      sudo: no
      command: python {{ vagrant_script_path }}/add_cluster_blueprint.py

    # Wait for up to 45 min for the cluster to come up
    - name: Install cluster via Ambari blueprint
      sudo: no
      command: python {{ vagrant_script_path }}/install_cluster.py
      async: 2700
      poll: 10
