---

- name: Distribution specific variables
  include_vars: "../defaults/{{ ansible_distribution }}.yml"

- name: Check for Couchbase Local Download
  stat: path=/vagrant/vagrant_deps/{{ couchbase_package }}
  register: couchbase_local_package

- name: Download Couchbase RPM locally
  get_url: url={{ couchbase_url }} dest=/vagrant/vagrant_deps/{{ couchbase_package }}
  when: not couchbase_local_package.stat.exists

# CentOS tasks
- include: CentOS.yml
  when: ansible_distribution == "CentOS"

# pip installs
- name: Install httplib2
  pip: name=httplib2

# Disable Transparent Huge Pages (THP) [http://docs.couchbase.com/admin/admin/Install/rhel-installing.html]
- name: Disable THP
  sudo: True
  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done' >> /etc/rc.local
  shell: echo 'for i in /sys/kernel/mm/*transparent_hugepage/defrag; do echo never > $i; done' >> /etc/rc.local
  shell: for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done
  shell: for i in /sys/kernel/mm/*transparent_hugepage/defrag; do echo never > $i; done
